name: Deployment
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:23.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run lint
  
  build:
    runs-on: ubuntu-latest
    container: docker:27.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t git.testgoofy.ch/lukas/application-compass:latest .
      - name: Push docker image
        run: docker push git.testgoofy.ch/lukas/application-compass:latest
