name: Deployment
on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:23.3.0
    steps:
      - run: pwd
      - run: ls -lA
      # - run: npm clean-install
      # - run: npm run lint
