name: Continuous Deployment
run-name: Continuous Deployment of ${{ github.sha }}
on:
  - push

jobs:
  Versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      version: ${{ steps.register_version.outputs.version }}
      major: ${{ steps.register_version.outputs.major }}
      minor: ${{ steps.register_version.outputs.minor }}
      patch: ${{ steps.register_version.outputs.patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install npm dependencies
        run: npm clean-install --force
      - name: Semantic Versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Register version
        id: register_version
        run: |
          if [ -f version.json ]; then
            cat version.json
            echo "version=$(jq -r .version version.json)" >> "$GITHUB_OUTPUT"
            echo "major=$(jq -r .major version.json)" >> "$GITHUB_OUTPUT"
            echo "minor=$(jq -r .minor version.json)" >> "$GITHUB_OUTPUT"
            echo "patch=$(jq -r .patch version.json)" >> "$GITHUB_OUTPUT"
          fi
  Release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:v${{ needs.Versioning.outputs.major }}
            ghcr.io/${{ github.repository }}:v${{ needs.Versioning.outputs.major }}.${{ needs.Versioning.outputs.minor }}
            ghcr.io/${{ github.repository }}:v${{ needs.Versioning.outputs.major }}.${{ needs.Versioning.outputs.minor }}.${{ needs.Versioning.outputs.patch }}
